name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy development
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      docker-image: ghcr.io/AplinkosMinisterija/biip-rusys-web
      enable-sentry: true
      build-args: |
        NODE_ENV=development
        VITE_SENTRY_DSN=https://bf21f87b264ed8a7586f44652cd0a935@sentry.biip.lt/15
        VITE_MAPS_HOST=https://dev-maps.biip.lt
